global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "jaeger"
    metrics_path: /metrics
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: "torrent-search"
    metrics_path: /metrics
    static_configs:
      - targets: ["torrent-search:8090"]

  - job_name: "torrent-engine"
    metrics_path: /metrics
    static_configs:
      - targets: ["torrentstream:8080"]
